# Generated by Django 4.2.2 on 2023-06-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupsecret',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usersecret',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='group',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='sender',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='groupsecret',
            name='group',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='receiver',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='sender',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='usersecret',
            name='other_user',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
